// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// VesselsColumns holds the columns for the "vessels" table.
	VesselsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "length_m", Type: field.TypeFloat64, Default: 0},
		{Name: "created_at", Type: field.TypeTime},
	}
	// VesselsTable holds the schema information for the "vessels" table.
	VesselsTable = &schema.Table{
		Name:       "vessels",
		Columns:    VesselsColumns,
		PrimaryKey: []*schema.Column{VesselsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		VesselsTable,
	}
)

func init() {
}
