// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"polyglot/ent/predicate"
	"polyglot/ent/vessel"
	"sync"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeVessel = "Vessel"
)

// VesselMutation represents an operation that mutates the Vessel nodes in the graph.
type VesselMutation struct {
	config
	op            Op
	typ           string
	id            *int
	name          *string
	length_m      *float64
	addlength_m   *float64
	created_at    *time.Time
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*Vessel, error)
	predicates    []predicate.Vessel
}

var _ ent.Mutation = (*VesselMutation)(nil)

// vesselOption allows management of the mutation configuration using functional options.
type vesselOption func(*VesselMutation)

// newVesselMutation creates new mutation for the Vessel entity.
func newVesselMutation(c config, op Op, opts ...vesselOption) *VesselMutation {
	m := &VesselMutation{
		config:        c,
		op:            op,
		typ:           TypeVessel,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withVesselID sets the ID field of the mutation.
func withVesselID(id int) vesselOption {
	return func(m *VesselMutation) {
		var (
			err   error
			once  sync.Once
			value *Vessel
		)
		m.oldValue = func(ctx context.Context) (*Vessel, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Vessel.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withVessel sets the old Vessel of the mutation.
func withVessel(node *Vessel) vesselOption {
	return func(m *VesselMutation) {
		m.oldValue = func(context.Context) (*Vessel, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m VesselMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m VesselMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *VesselMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *VesselMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Vessel.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetName sets the "name" field.
func (m *VesselMutation) SetName(s string) {
	m.name = &s
}

// Name returns the value of the "name" field in the mutation.
func (m *VesselMutation) Name() (r string, exists bool) {
	v := m.name
	if v == nil {
		return
	}
	return *v, true
}

// OldName returns the old "name" field's value of the Vessel entity.
// If the Vessel object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *VesselMutation) OldName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldName: %w", err)
	}
	return oldValue.Name, nil
}

// ResetName resets all changes to the "name" field.
func (m *VesselMutation) ResetName() {
	m.name = nil
}

// SetLengthM sets the "length_m" field.
func (m *VesselMutation) SetLengthM(f float64) {
	m.length_m = &f
	m.addlength_m = nil
}

// LengthM returns the value of the "length_m" field in the mutation.
func (m *VesselMutation) LengthM() (r float64, exists bool) {
	v := m.length_m
	if v == nil {
		return
	}
	return *v, true
}

// OldLengthM returns the old "length_m" field's value of the Vessel entity.
// If the Vessel object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *VesselMutation) OldLengthM(ctx context.Context) (v float64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldLengthM is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldLengthM requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldLengthM: %w", err)
	}
	return oldValue.LengthM, nil
}

// AddLengthM adds f to the "length_m" field.
func (m *VesselMutation) AddLengthM(f float64) {
	if m.addlength_m != nil {
		*m.addlength_m += f
	} else {
		m.addlength_m = &f
	}
}

// AddedLengthM returns the value that was added to the "length_m" field in this mutation.
func (m *VesselMutation) AddedLengthM() (r float64, exists bool) {
	v := m.addlength_m
	if v == nil {
		return
	}
	return *v, true
}

// ResetLengthM resets all changes to the "length_m" field.
func (m *VesselMutation) ResetLengthM() {
	m.length_m = nil
	m.addlength_m = nil
}

// SetCreatedAt sets the "created_at" field.
func (m *VesselMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *VesselMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the Vessel entity.
// If the Vessel object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *VesselMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *VesselMutation) ResetCreatedAt() {
	m.created_at = nil
}

// Where appends a list predicates to the VesselMutation builder.
func (m *VesselMutation) Where(ps ...predicate.Vessel) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the VesselMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *VesselMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Vessel, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *VesselMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *VesselMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Vessel).
func (m *VesselMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *VesselMutation) Fields() []string {
	fields := make([]string, 0, 3)
	if m.name != nil {
		fields = append(fields, vessel.FieldName)
	}
	if m.length_m != nil {
		fields = append(fields, vessel.FieldLengthM)
	}
	if m.created_at != nil {
		fields = append(fields, vessel.FieldCreatedAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *VesselMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case vessel.FieldName:
		return m.Name()
	case vessel.FieldLengthM:
		return m.LengthM()
	case vessel.FieldCreatedAt:
		return m.CreatedAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *VesselMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case vessel.FieldName:
		return m.OldName(ctx)
	case vessel.FieldLengthM:
		return m.OldLengthM(ctx)
	case vessel.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	}
	return nil, fmt.Errorf("unknown Vessel field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *VesselMutation) SetField(name string, value ent.Value) error {
	switch name {
	case vessel.FieldName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetName(v)
		return nil
	case vessel.FieldLengthM:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetLengthM(v)
		return nil
	case vessel.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	}
	return fmt.Errorf("unknown Vessel field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *VesselMutation) AddedFields() []string {
	var fields []string
	if m.addlength_m != nil {
		fields = append(fields, vessel.FieldLengthM)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *VesselMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case vessel.FieldLengthM:
		return m.AddedLengthM()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *VesselMutation) AddField(name string, value ent.Value) error {
	switch name {
	case vessel.FieldLengthM:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddLengthM(v)
		return nil
	}
	return fmt.Errorf("unknown Vessel numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *VesselMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *VesselMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *VesselMutation) ClearField(name string) error {
	return fmt.Errorf("unknown Vessel nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *VesselMutation) ResetField(name string) error {
	switch name {
	case vessel.FieldName:
		m.ResetName()
		return nil
	case vessel.FieldLengthM:
		m.ResetLengthM()
		return nil
	case vessel.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	}
	return fmt.Errorf("unknown Vessel field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *VesselMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *VesselMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *VesselMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *VesselMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *VesselMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *VesselMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *VesselMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown Vessel unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *VesselMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown Vessel edge %s", name)
}
