// Code generated by ent, DO NOT EDIT.

package ent

import (
	"polyglot/ent/schema"
	"polyglot/ent/vessel"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	vesselFields := schema.Vessel{}.Fields()
	_ = vesselFields
	// vesselDescLengthM is the schema descriptor for length_m field.
	vesselDescLengthM := vesselFields[1].Descriptor()
	// vessel.DefaultLengthM holds the default value on creation for the length_m field.
	vessel.DefaultLengthM = vesselDescLengthM.Default.(float64)
	// vesselDescCreatedAt is the schema descriptor for created_at field.
	vesselDescCreatedAt := vesselFields[2].Descriptor()
	// vessel.DefaultCreatedAt holds the default value on creation for the created_at field.
	vessel.DefaultCreatedAt = vesselDescCreatedAt.Default.(func() time.Time)
}
