// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"polyglot/ent/predicate"
	"polyglot/ent/vessel"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// VesselUpdate is the builder for updating Vessel entities.
type VesselUpdate struct {
	config
	hooks    []Hook
	mutation *VesselMutation
}

// Where appends a list predicates to the VesselUpdate builder.
func (_u *VesselUpdate) Where(ps ...predicate.Vessel) *VesselUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *VesselUpdate) SetName(v string) *VesselUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *VesselUpdate) SetNillableName(v *string) *VesselUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetLengthM sets the "length_m" field.
func (_u *VesselUpdate) SetLengthM(v float64) *VesselUpdate {
	_u.mutation.ResetLengthM()
	_u.mutation.SetLengthM(v)
	return _u
}

// SetNillableLengthM sets the "length_m" field if the given value is not nil.
func (_u *VesselUpdate) SetNillableLengthM(v *float64) *VesselUpdate {
	if v != nil {
		_u.SetLengthM(*v)
	}
	return _u
}

// AddLengthM adds value to the "length_m" field.
func (_u *VesselUpdate) AddLengthM(v float64) *VesselUpdate {
	_u.mutation.AddLengthM(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *VesselUpdate) SetCreatedAt(v time.Time) *VesselUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *VesselUpdate) SetNillableCreatedAt(v *time.Time) *VesselUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// Mutation returns the VesselMutation object of the builder.
func (_u *VesselUpdate) Mutation() *VesselMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *VesselUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *VesselUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *VesselUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *VesselUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *VesselUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(vessel.Table, vessel.Columns, sqlgraph.NewFieldSpec(vessel.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(vessel.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.LengthM(); ok {
		_spec.SetField(vessel.FieldLengthM, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedLengthM(); ok {
		_spec.AddField(vessel.FieldLengthM, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(vessel.FieldCreatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{vessel.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// VesselUpdateOne is the builder for updating a single Vessel entity.
type VesselUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *VesselMutation
}

// SetName sets the "name" field.
func (_u *VesselUpdateOne) SetName(v string) *VesselUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *VesselUpdateOne) SetNillableName(v *string) *VesselUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetLengthM sets the "length_m" field.
func (_u *VesselUpdateOne) SetLengthM(v float64) *VesselUpdateOne {
	_u.mutation.ResetLengthM()
	_u.mutation.SetLengthM(v)
	return _u
}

// SetNillableLengthM sets the "length_m" field if the given value is not nil.
func (_u *VesselUpdateOne) SetNillableLengthM(v *float64) *VesselUpdateOne {
	if v != nil {
		_u.SetLengthM(*v)
	}
	return _u
}

// AddLengthM adds value to the "length_m" field.
func (_u *VesselUpdateOne) AddLengthM(v float64) *VesselUpdateOne {
	_u.mutation.AddLengthM(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *VesselUpdateOne) SetCreatedAt(v time.Time) *VesselUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *VesselUpdateOne) SetNillableCreatedAt(v *time.Time) *VesselUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// Mutation returns the VesselMutation object of the builder.
func (_u *VesselUpdateOne) Mutation() *VesselMutation {
	return _u.mutation
}

// Where appends a list predicates to the VesselUpdate builder.
func (_u *VesselUpdateOne) Where(ps ...predicate.Vessel) *VesselUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *VesselUpdateOne) Select(field string, fields ...string) *VesselUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Vessel entity.
func (_u *VesselUpdateOne) Save(ctx context.Context) (*Vessel, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *VesselUpdateOne) SaveX(ctx context.Context) *Vessel {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *VesselUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *VesselUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *VesselUpdateOne) sqlSave(ctx context.Context) (_node *Vessel, err error) {
	_spec := sqlgraph.NewUpdateSpec(vessel.Table, vessel.Columns, sqlgraph.NewFieldSpec(vessel.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Vessel.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, vessel.FieldID)
		for _, f := range fields {
			if !vessel.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != vessel.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(vessel.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.LengthM(); ok {
		_spec.SetField(vessel.FieldLengthM, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedLengthM(); ok {
		_spec.AddField(vessel.FieldLengthM, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(vessel.FieldCreatedAt, field.TypeTime, value)
	}
	_node = &Vessel{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{vessel.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
