// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"polyglot/ent/vessel"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Vessel is the model entity for the Vessel schema.
type Vessel struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// LengthM holds the value of the "length_m" field.
	LengthM float64 `json:"length_m,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Vessel) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case vessel.FieldLengthM:
			values[i] = new(sql.NullFloat64)
		case vessel.FieldID:
			values[i] = new(sql.NullInt64)
		case vessel.FieldName:
			values[i] = new(sql.NullString)
		case vessel.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Vessel fields.
func (_m *Vessel) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case vessel.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case vessel.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case vessel.FieldLengthM:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field length_m", values[i])
			} else if value.Valid {
				_m.LengthM = value.Float64
			}
		case vessel.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Vessel.
// This includes values selected through modifiers, order, etc.
func (_m *Vessel) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Vessel.
// Note that you need to call Vessel.Unwrap() before calling this method if this Vessel
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Vessel) Update() *VesselUpdateOne {
	return NewVesselClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Vessel entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Vessel) Unwrap() *Vessel {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Vessel is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Vessel) String() string {
	var builder strings.Builder
	builder.WriteString("Vessel(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("length_m=")
	builder.WriteString(fmt.Sprintf("%v", _m.LengthM))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Vessels is a parsable slice of Vessel.
type Vessels []*Vessel
