// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"polyglot/ent/vessel"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// VesselCreate is the builder for creating a Vessel entity.
type VesselCreate struct {
	config
	mutation *VesselMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *VesselCreate) SetName(v string) *VesselCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetLengthM sets the "length_m" field.
func (_c *VesselCreate) SetLengthM(v float64) *VesselCreate {
	_c.mutation.SetLengthM(v)
	return _c
}

// SetNillableLengthM sets the "length_m" field if the given value is not nil.
func (_c *VesselCreate) SetNillableLengthM(v *float64) *VesselCreate {
	if v != nil {
		_c.SetLengthM(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *VesselCreate) SetCreatedAt(v time.Time) *VesselCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *VesselCreate) SetNillableCreatedAt(v *time.Time) *VesselCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// Mutation returns the VesselMutation object of the builder.
func (_c *VesselCreate) Mutation() *VesselMutation {
	return _c.mutation
}

// Save creates the Vessel in the database.
func (_c *VesselCreate) Save(ctx context.Context) (*Vessel, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *VesselCreate) SaveX(ctx context.Context) *Vessel {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *VesselCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *VesselCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *VesselCreate) defaults() {
	if _, ok := _c.mutation.LengthM(); !ok {
		v := vessel.DefaultLengthM
		_c.mutation.SetLengthM(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := vessel.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *VesselCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Vessel.name"`)}
	}
	if _, ok := _c.mutation.LengthM(); !ok {
		return &ValidationError{Name: "length_m", err: errors.New(`ent: missing required field "Vessel.length_m"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Vessel.created_at"`)}
	}
	return nil
}

func (_c *VesselCreate) sqlSave(ctx context.Context) (*Vessel, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *VesselCreate) createSpec() (*Vessel, *sqlgraph.CreateSpec) {
	var (
		_node = &Vessel{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(vessel.Table, sqlgraph.NewFieldSpec(vessel.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(vessel.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.LengthM(); ok {
		_spec.SetField(vessel.FieldLengthM, field.TypeFloat64, value)
		_node.LengthM = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(vessel.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// VesselCreateBulk is the builder for creating many Vessel entities in bulk.
type VesselCreateBulk struct {
	config
	err      error
	builders []*VesselCreate
}

// Save creates the Vessel entities in the database.
func (_c *VesselCreateBulk) Save(ctx context.Context) ([]*Vessel, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Vessel, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*VesselMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *VesselCreateBulk) SaveX(ctx context.Context) []*Vessel {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *VesselCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *VesselCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
