// Code generated by ent, DO NOT EDIT.

package vessel

import (
	"polyglot/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Vessel {
	return predicate.Vessel(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Vessel {
	return predicate.Vessel(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Vessel {
	return predicate.Vessel(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Vessel {
	return predicate.Vessel(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Vessel {
	return predicate.Vessel(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Vessel {
	return predicate.Vessel(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Vessel {
	return predicate.Vessel(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Vessel {
	return predicate.Vessel(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Vessel {
	return predicate.Vessel(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Vessel {
	return predicate.Vessel(sql.FieldEQ(FieldName, v))
}

// LengthM applies equality check predicate on the "length_m" field. It's identical to LengthMEQ.
func LengthM(v float64) predicate.Vessel {
	return predicate.Vessel(sql.FieldEQ(FieldLengthM, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Vessel {
	return predicate.Vessel(sql.FieldEQ(FieldCreatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Vessel {
	return predicate.Vessel(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Vessel {
	return predicate.Vessel(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Vessel {
	return predicate.Vessel(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Vessel {
	return predicate.Vessel(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Vessel {
	return predicate.Vessel(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Vessel {
	return predicate.Vessel(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Vessel {
	return predicate.Vessel(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Vessel {
	return predicate.Vessel(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Vessel {
	return predicate.Vessel(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Vessel {
	return predicate.Vessel(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Vessel {
	return predicate.Vessel(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Vessel {
	return predicate.Vessel(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Vessel {
	return predicate.Vessel(sql.FieldContainsFold(FieldName, v))
}

// LengthMEQ applies the EQ predicate on the "length_m" field.
func LengthMEQ(v float64) predicate.Vessel {
	return predicate.Vessel(sql.FieldEQ(FieldLengthM, v))
}

// LengthMNEQ applies the NEQ predicate on the "length_m" field.
func LengthMNEQ(v float64) predicate.Vessel {
	return predicate.Vessel(sql.FieldNEQ(FieldLengthM, v))
}

// LengthMIn applies the In predicate on the "length_m" field.
func LengthMIn(vs ...float64) predicate.Vessel {
	return predicate.Vessel(sql.FieldIn(FieldLengthM, vs...))
}

// LengthMNotIn applies the NotIn predicate on the "length_m" field.
func LengthMNotIn(vs ...float64) predicate.Vessel {
	return predicate.Vessel(sql.FieldNotIn(FieldLengthM, vs...))
}

// LengthMGT applies the GT predicate on the "length_m" field.
func LengthMGT(v float64) predicate.Vessel {
	return predicate.Vessel(sql.FieldGT(FieldLengthM, v))
}

// LengthMGTE applies the GTE predicate on the "length_m" field.
func LengthMGTE(v float64) predicate.Vessel {
	return predicate.Vessel(sql.FieldGTE(FieldLengthM, v))
}

// LengthMLT applies the LT predicate on the "length_m" field.
func LengthMLT(v float64) predicate.Vessel {
	return predicate.Vessel(sql.FieldLT(FieldLengthM, v))
}

// LengthMLTE applies the LTE predicate on the "length_m" field.
func LengthMLTE(v float64) predicate.Vessel {
	return predicate.Vessel(sql.FieldLTE(FieldLengthM, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Vessel {
	return predicate.Vessel(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Vessel {
	return predicate.Vessel(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Vessel {
	return predicate.Vessel(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Vessel {
	return predicate.Vessel(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Vessel {
	return predicate.Vessel(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Vessel {
	return predicate.Vessel(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Vessel {
	return predicate.Vessel(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Vessel {
	return predicate.Vessel(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Vessel) predicate.Vessel {
	return predicate.Vessel(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Vessel) predicate.Vessel {
	return predicate.Vessel(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Vessel) predicate.Vessel {
	return predicate.Vessel(sql.NotPredicates(p))
}
